export const plotDataDefaultState = [
  {
    plotNumber: '1',
    name: 'House',
    sunLight: 'full-sun',
    blockType: 'house',
    size: 3,
    rainExposure: 'partially',
    growable: true,
  },
  {
    plotNumber: '2',
    name: '',
    sunLight: 'part-sun',
    blockType: 'path',
    size: 3,
    rainExposure: 'partially',
    growable: true,
  },
  {
    plotNumber: '4',
    name: '',
    sunLight: 'full-sun',
    blockType: 'path',
    size: 3,
    rainExposure: 'partially',
    growable: true,
  },
  {
    plotNumber: '6',
    name: '',
    sunLight: 'full-sun',
    blockType: 'grass',
    size: 3,
    rainExposure: 'partially',
    growable: true,
  },
  {
    plotNumber: '7',
    name: 'Berries',
    sunLight: 'full-sun',
    blockType: 'garden',
    size: 3,
    rainExposure: 'partially',
    growable: true,
  },
  {
    plotNumber: '8',
    name: 'Glasshouse',
    sunLight: 'full-sun',
    blockType: 'garden',
    size: 3,
    rainExposure: 'partially',
    growable: true,
  },
  {
    plotNumber: '9',
    name: '',
    sunLight: 'full-sun',
    blockType: 'grass',
    size: 3,
    rainExposure: 'partially',
    growable: true,
  },
  {
    plotNumber: '10',
    name: 'Back fence',
    sunLight: 'full-sun',
    blockType: 'garden',
    size: 3,
    rainExposure: 'partially',
    growable: true,
  },
  {
    plotNumber: '3',
    name: 'Kitchen garden',
    sunLight: 'full-shade',
    blockType: 'garden',
    size: 3,
    rainExposure: 'partially',
    growable: true,
  },
]

export const layoutDefaultState = [
  { i: '1', x: 0, y: 0, w: 11, h: 12 },
  { i: '2', x: 11, y: 0, w: 3, h: 16 },
  { i: '3', x: 14, y: 0, w: 12, h: 20 },
  { i: '4', x: 0, y: 6, w: 11, h: 4 },
  { i: '6', x: 26, y: 3, w: 21, h: 14 },
  { i: '7', x: 26, y: 0, w: 21, h: 6 },
  { i: '8', x: 0, y: 8, w: 14, h: 18 },
  { i: '9', x: 14, y: 10, w: 33, h: 6 },
  { i: '10', x: 14, y: 13, w: 33, h: 8 },
]
