/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export const seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('users').del()
  await knex('users').insert([
    {
      id: 1,
      auth0_id: 'auth0|123',
      username: 'gardener_john',
      location: 'New York',
      summer_start_month: 'June',
    },
    {
      id: 2,
      auth0_id: 'auth0|456',
      username: 'plantlover_jane',
      location: 'California',
      summer_start_month: 'March',
    },
    {
      id: 3,
      auth0_id: 'auth0|789',
      username: 'green_thumb_joe',
      location: 'Wellington',
      summer_start_month: 'December',
    },
  ])
  await knex('gardens').del()
  await knex('gardens').insert([
    {
      id: 1,
      user_id: 1,
      layout: `[  { i: '1', x: 0, y: 0, w: 11, h: 12 },
  { i: '2', x: 11, y: 0, w: 3, h: 16 },
  { i: '3', x: 14, y: 0, w: 12, h: 20 }]`,
      name: 'Kitchen',
    },
    {
      id: 2,
      user_id: 2,
      layout: `[ { i: '4', x: 0, y: 6, w: 11, h: 4 },
  { i: '6', x: 26, y: 3, w: 21, h: 14 },
  { i: '7', x: 26, y: 0, w: 21, h: 6 }]`,
      name: 'front',
    },
    {
      id: 3,
      user_id: 3,
      layout: `[{ i: '8', x: 0, y: 8, w: 14, h: 18 },
  { i: '9', x: 14, y: 10, w: 33, h: 6 },
  { i: '10', x: 14, y: 13, w: 33, h: 8 }]`,
      name: 'back',
    },
  ])
  await knex('plants').del()
  await knex('plants').insert([
    {
      id: 1,
      name: 'Tomato',
      difficulty: 'Medium',
      planting_starts: 'early-spring',
      planting_ends: 'summer',
      watering_frequency: 'Daily',
      sun_level: 'full-sun',
      cycle: 'Annual',
      days_from_seed_until_seedling: 40,
      days_from_planting_until_harvest: 180,
    },
    {
      id: 2,
      name: 'Basil',
      difficulty: 'Easy',
      planting_starts: 'late-summer',
      planting_ends: 'early-winter',
      watering_frequency: 'Twice a week',
      sun_level: 'part-sun',
      cycle: 'Annual',
      days_from_seed_until_seedling: 20,
      days_from_planting_until_harvest: 90,
    },
    {
      id: 3,
      name: 'Carrot',
      difficulty: 'Hard',
      planting_starts: 'early-spring',
      planting_ends: 'late-spring',
      watering_frequency: 'Every other day',
      sun_level: 'full-sun',
      cycle: 'Biennial',
      days_from_seed_until_seedling: 0,
      days_from_planting_until_harvest: 190,
    },
    {
      id: 4,
      name: 'Cauliflower',
      difficulty: 'Medium',
      planting_starts: 'summer',
      planting_ends: 'winter',
      watering_frequency: 'Daily',
      sun_level: 'full-sun to part-sun',
      cycle: 'Annual',
      days_from_seed_until_seedling: 40,
      days_from_planting_until_harvest: 180,
    },
    {
      id: 5,
      name: 'Broccoli',
      difficulty: 'Easy',
      planting_starts: 'summer',
      planting_ends: 'late-summer',
      watering_frequency: 'Twice a week',
      sun_level: 'part-sun to full-shade',
      cycle: 'Annual',
      days_from_seed_until_seedling: 20,
      days_from_planting_until_harvest: 90,
    },
    {
      id: 6,
      name: 'Silverbeet',
      difficulty: 'Easy',
      planting_starts: 'year-round',
      planting_ends: 'year-round',
      watering_frequency: 'Every other day',
      sun_level: 'full-shade',
      cycle: 'Biennial',
      days_from_seed_until_seedling: 0,
      days_from_planting_until_harvest: 190,
    },
  ])

  await knex('plant_care_data').del()
  await knex('plant_care_data').insert([
    {
      id: 1,
      plantName: 'Tomato',
      scientificName: 'Solanum lycopersicum',
      description:
        'The tomato is a widely cultivated plant species, producing edible red fruits, commonly known as tomatoes.',
      soil: 'Well-drained',
      sunlight: 'Full sun',
      watering: 'Medium',
      fertilization: 'Regularly',
      pruning: 'Prune regularly',
      pests: 'Watch for insects',
      diseases: 'Protect from disease',
      indoorsPlantingTime: 'Start seeds indoors August - September',
      outdoorsPlantingTime: 'Transplant outdoors October - November',
      spacing: '0.6 - 1.0 metres',
      plantingTime: 'October - November',
      havestingTime: 'Summer',
      harvestingTips: 'Harvest when red',
    },
    {
      id: 2,
      plantName: 'Potato',
      scientificName: 'Solanum tuberosum',
      description: 'A starchy tuberous crop grown for its edible tubers.',
      soil: 'Well drained, loose soil',
      sunlight: 'Full sun',
      watering: 'Medium',
      fertilization: 'Regularly',
      pruning: 'Remove any diseased foliage',
      pests: 'Aphids, Colorado potato beetles',
      diseases: 'Late blight, early blight',
      indoorsPlantingTime: 'Not applicable',
      outdoorsPlantingTime: 'Spring',
      spacing: '0.3 - 0.6 meters',
      plantingTime: 'August - October',
      havestingTime: 'Summer',
      harvestingTips: 'Harvest when tubers are firm and mature',
    },
    {
      id: 3,
      plantName: 'Zucchini',
      scientificName: 'Cucurbita pepo',
      description:
        'Zucchini is a summer squash with a mild flavor and a versatile range of culinary uses.',
      soil: 'Well-drained',
      sunlight: 'Full sun',
      watering: 'Medium',
      fertilization: 'Regularly',
      pruning: 'Pinch off blossoms',
      pests: 'Squash bugs',
      diseases: 'Powdery mildew',
      indoorsPlantingTime: 'Start seeds indoors August - September',
      outdoorsPlantingTime: 'Transplant outdoors October - November',
      spacing: '0.6 - 1 meter',
      plantingTime: 'Spring',
      havestingTime: 'Summer to autumn',
      harvestingTips: 'Harvest zucchini when small and tender',
    },
  ])

  await knex('user_desired_plants').del()
  await knex('user_desired_plants').insert([
    { id: 1, user_id: 1, plant_id: 1 },
    { id: 2, user_id: 1, plant_id: 2 },
    { id: 3, user_id: 1, plant_id: 3 },
    { id: 4, user_id: 2, plant_id: 1 },
    { id: 5, user_id: 2, plant_id: 2 },
    { id: 6, user_id: 2, plant_id: 3 },
    { id: 7, user_id: 3, plant_id: 1 },
    { id: 8, user_id: 3, plant_id: 2 },
    { id: 9, user_id: 3, plant_id: 3 },
  ])
  await knex('plots').del()
  await knex('plots').insert([
    {
      id: 1,
      garden_id: 1,
      plot_number: 1,
      sun_level: 'part-sun',
      plot_type: 'house',
      size: 5,
      growable: false,
    },
    {
      id: 2,
      garden_id: 1,
      plot_number: 2,
      sun_level: 'full-sun',
      plot_type: 'path',
      size: 4,
      growable: true,
    },
    {
      id: 3,
      garden_id: 1,
      plot_number: 3,
      sun_level: 'full-shade',
      plot_type: 'garden',
      size: 4,
      growable: true,
    },
    {
      id: 4,
      garden_id: 2,
      plot_number: 1,
      sun_level: 'part-sun',
      plot_type: 'garden',
      size: 5,
      growable: true,
    },
    {
      id: 5,
      garden_id: 2,
      plot_number: 2,
      sun_level: 'full-sun',
      plot_type: 'garden',
      size: 4,
      growable: true,
    },
    {
      id: 6,
      garden_id: 2,
      plot_number: 3,
      sun_level: 'full-shade',
      plot_type: 'garden',
      size: 2,
      growable: true,
    },
    {
      id: 7,
      garden_id: 3,
      plot_number: 1,
      sun_level: 'part-sun',
      plot_type: 'grass',
      size: 5,
      growable: true,
    },
    {
      id: 8,
      garden_id: 3,
      plot_number: 2,
      sun_level: 'full-sun',
      plot_type: 'grass',
      size: 4,
      growable: true,
    },
    {
      id: 9,
      garden_id: 3,
      plot_number: 3,
      sun_level: 'full-shade',
      plot_type: 'garden',
      size: 2,
      growable: true,
    },
  ])
  await knex('plots_plants').del()
  await knex('plots_plants').insert([
    {
      id: 1,
      plant_id: 1,
      plot_id: 1,
      date_planted: '2024-03-01',
      last_watered: '2024-03-15',
      watering_history: '[2024-03-15]',
      user_id: 1,
      name: 'tomato 1',
    },
    {
      id: 2,
      plant_id: 2,
      plot_id: 2,
      date_planted: '2024-04-01',
      last_watered: '2024-04-10',
      watering_history: '[2024-03-15]',
      user_id: 1,
      name: 'tomato 2',
    },
    {
      id: 3,
      plant_id: 3,
      plot_id: 3,
      date_planted: '2024-02-15',
      last_watered: '2024-02-20',
      watering_history: '[2024-03-15]',
      user_id: 1,
      name: 'tomato 3',
    },
    {
      id: 4,
      plant_id: 1,
      plot_id: 4,
      date_planted: '2024-03-01',
      last_watered: '2024-03-15',
      watering_history: '[2024-03-15]',
      user_id: 2,
      name: 'cucumber 1',
    },
    {
      id: 5,
      plant_id: 2,
      plot_id: 5,
      date_planted: '2024-04-01',
      last_watered: '2024-04-10',
      watering_history: '[2024-03-15]',
      user_id: 2,
      name: 'cucumber 2',
    },
    {
      id: 6,
      plant_id: 3,
      plot_id: 6,
      date_planted: '2024-02-15',
      last_watered: '2024-02-20',
      watering_history: '[2024-03-15]',
      user_id: 2,
      name: 'cucumber 3',
    },
    {
      id: 7,
      plant_id: 1,
      plot_id: 7,
      date_planted: '2024-03-01',
      last_watered: '2024-03-15',
      watering_history: '[2024-03-15]',
      user_id: 3,
      name: 'potato 1',
    },
    {
      id: 8,
      plant_id: 2,
      plot_id: 8,
      date_planted: '2024-04-01',
      last_watered: '2024-04-10',
      watering_history: '[2024-03-15]',
      user_id: 3,
      name: 'potato 2',
    },
    {
      id: 9,
      plant_id: 3,
      plot_id: 9,
      date_planted: '2024-02-15',
      last_watered: '2024-02-20',
      watering_history: '[2024-03-15]',
      user_id: 3,
      name: 'potato 3',
    },
  ])

  // await knex('plant_notes').del()
  // await knex('plant_notes').insert([
  //   {id: 1, plot_plant_id: 1, date: '2024-03-16', note: 'Plant is growing well.' },
  //   {id: 2, plot_plant_id: 2, date: '2024-04-12', note: 'Leaves are green and healthy.' },
  //   {id: 3, plot_plant_id: 3, date: '2024-02-22', note: 'Showing signs of growth.' },
  //   {id: 4, plot_plant_id: 4, date: '2024-03-16', note: 'Plant is growing well.' },
  //   {id: 5, plot_plant_id: 5, date: '2024-04-12', note: 'Leaves are green and healthy.' },
  //   {id: 6, plot_plant_id: 6, date: '2024-02-22', note: 'Showing signs of growth.' },
  //   {id: 7, plot_plant_id: 7, date: '2024-03-16', note: 'Plant is growing well.' },
  //   {id: 8, plot_plant_id: 8, date: '2024-04-12', note: 'Leaves are green and healthy.' },
  //   {id: 9, plot_plant_id: 9, date: '2024-02-22', note: 'Showing signs of growth.' },
  // ]);
  // await knex('images').del()
  // await knex('images').insert([
  //   {id: 1, plot_notes_id: 1, image: 'image1.jpg' },
  //   {id: 2, plot_notes_id: 2, image: 'image2.jpg' },
  //   {id: 3, plot_notes_id: 3, image: 'image3.jpg' }
  // ]);
}
