/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export const seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('users').del()
  await knex('users').insert([
    {
      id: 1,
      auth0_id: 'google-oauth2|118294311203163729435',
      username: 'gardener_john',
      location: 'New York',
      summer_start_month: 'June',
    },
    {
      id: 2,
      auth0_id: 'auth0|456',
      username: 'plantlover_jane',
      location: 'California',
      summer_start_month: 'March',
    },
    {
      id: 3,
      auth0_id: 'auth0|789',
      username: 'green_thumb_joe',
      location: 'Wellington',
      summer_start_month: 'December',
    },
  ])
  await knex('gardens').del()
  await knex('gardens').insert([
    {
      id: 1,
      user_id: 1,
      layout: `[  { i: '1', x: 0, y: 0, w: 11, h: 12 },
  { i: '2', x: 11, y: 0, w: 3, h: 16 },
  { i: '3', x: 14, y: 0, w: 12, h: 20 }]`,
      name: 'Kitchen',
    },
    {
      id: 2,
      user_id: 2,
      layout: `[ { i: '4', x: 0, y: 6, w: 11, h: 4 },
  { i: '6', x: 26, y: 3, w: 21, h: 14 },
  { i: '7', x: 26, y: 0, w: 21, h: 6 }]`,
      name: 'front',
    },
    {
      id: 3,
      user_id: 3,
      layout: `[{ i: '8', x: 0, y: 8, w: 14, h: 18 },
  { i: '9', x: 14, y: 10, w: 33, h: 6 },
  { i: '10', x: 14, y: 13, w: 33, h: 8 }]`,
      name: 'back',
    },
  ])
  await knex('plants').del()
  await knex('plants').insert([
    {
      id: 1,
      name: 'Tomato',
      icon_src: '/images/flat-icons/veg-fruit-icons/tomato.png',
      photo_src: '/images/photos/tomatoes.jpg',
      difficulty: 'Medium',
      planting_starts: 'early-spring',
      planting_ends: 'summer',
      watering_frequency: 'Daily',
      sun_level: 'full-sun',
      cycle: 'Annual',
      days_from_seed_until_seedling: 40,
      days_from_planting_until_harvest: 180,
    },
    {
      id: 2,
      name: "Potato",
      icon_src: "/images/flat-icons/veg-fruit-icons/potato.png",
      photo_src: "/images/photos/potato.jpg",
      difficulty: "Moderate",
      planting_starts: "early spring",
      planting_ends: "mid-spring",
      watering_frequency: "Regularly, keep soil evenly moist",
      sun_level: "full-sun",
      cycle: "Annual",
      days_from_seed_until_seedling: null,
      days_from_planting_until_harvest: 90
    },
    {
      id: 3,
      name: "Zucchini",
      icon_src: "/images/flat-icons/veg-fruit-icons/zucchini.png",
      photo_src: "/images/photos/zucchini.jpg",
      difficulty: "Easy",
      planting_starts: "spring",
      planting_ends: "early summer",
      watering_frequency: "Regularly, keep soil moist",
      sun_level: "full-sun",
      cycle: "Annual",
      days_from_seed_until_seedling: 7,
      days_from_planting_until_harvest: 50
    },
    {
      id: 4,
      name: 'Cauliflower',
      icon_src: '/images/flat-icons/veg-fruit-icons/cauliflower.png',
      photo_src: '/images/photos/cauliflower.jpg',
      difficulty: 'Medium',
      planting_starts: 'summer',
      planting_ends: 'winter',
      watering_frequency: 'Daily',
      sun_level: 'full-sun to part-sun',
      cycle: 'Annual',
      days_from_seed_until_seedling: 40,
      days_from_planting_until_harvest: 180,
    },
    {
      id: 5,
      name: 'Broccoli',
      icon_src: '/images/flat-icons/veg-fruit-icons/broccoli.png',
      photo_src: '/images/photos/broccoli.jpg',
      difficulty: 'Easy',
      planting_starts: 'summer',
      planting_ends: 'late-summer',
      watering_frequency: 'Twice a week',
      sun_level: 'part-sun to full-shade',
      cycle: 'Annual',
      days_from_seed_until_seedling: 20,
      days_from_planting_until_harvest: 90,
    },
    {
      id: 6,
      name: 'Silverbeet',
      icon_src: '/images/flat-icons/veg-fruit-icons/chard.png',
      photo_src: '/images/photos/silverbeet.jpg',
      difficulty: 'Easy',
      planting_starts: 'year-round',
      planting_ends: 'year-round',
      watering_frequency: 'Every other day',
      sun_level: 'full-shade',
      cycle: 'Biennial',
      days_from_seed_until_seedling: 0,
      days_from_planting_until_harvest: 190,
    },
    {
      id: 7,
      name: 'Asparagus',
      icon_src: '/images/flat-icons/veg-fruit-icons/asparagus.png',
      photo_src: '/images/photos/asparagus.jpg',
      difficulty: 'Hard',
      planting_starts: 'early-spring',
      planting_ends: 'late-spring',
      watering_frequency: 'Weekly',
      sun_level: 'full-sun',
      cycle: 'Perennial',
      days_from_seed_until_seedling: 25,
      days_from_planting_until_harvest: 850,
    },
    {
      id: 8,
      name: 'Blackberry',
      icon_src: '/images/flat-icons/veg-fruit-icons/blackberry.png',
      photo_src: '/images/photos/blackberries.jpg',
      difficulty: 'Medium',
      planting_starts: 'early-spring',
      planting_ends: 'late-spring',
      watering_frequency: 'Weekly',
      sun_level: 'full-sun',
      cycle: 'Perennial',
      days_from_seed_until_seedling: 35,
      days_from_planting_until_harvest: 500
    },
    {
      id: 9,
      name: 'Blueberry',
      icon_src: '/images/flat-icons/veg-fruit-icons/blueberry.png',
      photo_src: '/images/photos/blueberries.jpg',
      difficulty: 'Medium to Hard',
      planting_starts: 'early-spring',
      planting_ends: 'late-spring',
      watering_frequency: 'Weekly',
      sun_level: 'full-sun to partial-shade',
      cycle: 'Perennial',
      days_from_seed_until_seedling: 45,
      days_from_planting_until_harvest: 875
    },
    {
      id: 10,
      name: 'Bok Choy',
      icon_src: '/images/flat-icons/veg-fruit-icons/bokchoi.png',
      photo_src: '/images/photos/bokchoi.jpg',
      difficulty: 'Easy',
      planting_starts: 'early-spring',
      planting_ends: 'late-summer',
      watering_frequency: 'Every 2-3 days',
      sun_level: 'partial-sun to full-sun',
      cycle: 'Annual',
      days_from_seed_until_seedling: 8,
      days_from_planting_until_harvest: 55
    },
    {
      id: 11,
      name: 'Broad Beans',
      icon_src: '/images/flat-icons/veg-fruit-icons/broadbeans.png',
      photo_src: '/images/photos/broad-beans.jpg',
      difficulty: 'Easy',
      planting_starts: 'early-spring',
      planting_ends: 'late-spring',
      watering_frequency: 'Weekly',
      sun_level: 'full-sun',
      cycle: 'Annual',
      days_from_seed_until_seedling: 10,
      days_from_planting_until_harvest: 90
    },
    {
      id: 12,
      name: "Capsicum",
      icon_src: "/images/flat-icons/veg-fruit-icons/capsicum.png",
      photo_src: "/images/photos/capsicum.jpg",
      difficulty: "Medium",
      planting_starts: "early-spring",
      planting_ends: "summer",
      watering_frequency: "Regularly, when soil is dry",
      sun_level: "full-sun",
      cycle: "Annual",
      days_from_seed_until_seedling: 10,
      days_from_planting_until_harvest: 75
    },
    {
      id: 13,
      name: "Celery",
      icon_src: "/images/flat-icons/veg-fruit-icons/celery.png",
      photo_src: "/images/photos/celery.jpg",
      difficulty: "Medium",
      planting_starts: "early-spring",
      planting_ends: "mid-summer",
      watering_frequency: "Regularly, keep soil consistently moist",
      sun_level: "partial-sun to full-sun",
      cycle: "Biennial",
      days_from_seed_until_seedling: 14,
      days_from_planting_until_harvest: 120
    },
    {
      id: 14,
      name: "Coriander",
      icon_src: "/images/flat-icons/veg-fruit-icons/coriander.png",
      photo_src: "/images/photos/coriander.jpg",
      difficulty: "Easy",
      planting_starts: "early-spring",
      planting_ends: "late-summer",
      watering_frequency: "Regularly, keep soil moist but not waterlogged",
      sun_level: "partial-sun to full-sun",
      cycle: "Annual",
      days_from_seed_until_seedling: 10,
      days_from_planting_until_harvest: 40
    },
    {
      id: 15,
      name: "Corn",
      icon_src: "/images/flat-icons/veg-fruit-icons/corn.png",
      photo_src: "/images/photos/corn.jpg",
      difficulty: "Medium",
      planting_starts: "spring",
      planting_ends: "early-summer",
      watering_frequency: "Regularly, keep soil moist",
      sun_level: "full-sun",
      cycle: "Annual",
      days_from_seed_until_seedling: 10,
      days_from_planting_until_harvest: 80
    },
    {
      id: 16,
      name: "Courgette",
      icon_src: "/images/flat-icons/veg-fruit-icons/courgette.png",
      photo_src: "/images/photos/courgette.jpg",
      difficulty: "Easy",
      planting_starts: "spring",
      planting_ends: "early-summer",
      watering_frequency: "Regularly, keep soil moist",
      sun_level: "full-sun",
      cycle: "Annual",
      days_from_seed_until_seedling: 10,
      days_from_planting_until_harvest: 55
    },
    {
      id: 17,
      name: "Spring Onion",
      icon_src: "/images/flat-icons/veg-fruit-icons/springonion.png",
      photo_src: "/images/photos/springonion.jpg",
      difficulty: "Easy",
      planting_starts: "early spring",
      planting_ends: "mid-summer",
      watering_frequency: "Regularly, keep soil moist",
      sun_level: "full-sun to partial-shade",
      cycle: "Annual",
      days_from_seed_until_seedling: 7,
      days_from_planting_until_harvest: 60
    },
    {
      id: 18,
      name: 'Apple',
      icon_src: '/images/flat-icons/veg-fruit-icons/apple.png',
      photo_src: '/images/photos/apples.jpg',
      difficulty: 'Medium',
      planting_starts: 'late-winter',
      planting_ends: 'early-spring',
      watering_frequency: 'Weekly',
      sun_level: 'full-sun',
      cycle: 'Perennial',
      days_from_seed_until_seedling: 60,
      days_from_planting_until_harvest: 365,
    },
    {
      id: 19,
      name: 'Arugula',
      icon_src: '/images/flat-icons/veg-fruit-icons/arugula.png',
      photo_src: '/images/photos/arugula.jpg',
      difficulty: 'Easy',
      planting_starts: 'early-spring',
      planting_ends: 'late-summer',
      watering_frequency: 'Every 2-3 days',
      sun_level: 'partial-sun',
      cycle: 'Annual',
      days_from_seed_until_seedling: 7,
      days_from_planting_until_harvest: 30,
    },
    {
      id: 20,
      name: "Cucumber",
      icon_src: "/images/flat-icons/veg-fruit-icons/cucumber.png",
      photo_src: "/images/photos/cucumber.jpg",
      difficulty: "Easy",
      planting_starts: "spring",
      planting_ends: "early-summer",
      watering_frequency: "Regularly, keep soil moist",
      sun_level: "full-sun",
      cycle: "Annual",
      days_from_seed_until_seedling: 7,
      days_from_planting_until_harvest: 60
    },
    {
      id: 21,
      name: "Eggplant",
      icon_src: "/images/flat-icons/veg-fruit-icons/eggplant.png",
      photo_src: "/images/photos/eggplant.jpg",
      difficulty: "Medium",
      planting_starts: "spring",
      planting_ends: "early-summer",
      watering_frequency: "Regularly, keep soil moist",
      sun_level: "full-sun",
      cycle: "Annual",
      days_from_seed_until_seedling: 10,
      days_from_planting_until_harvest: 80
    },
    {
      id: 22,
      name: "Feijoa",
      icon_src: "/images/flat-icons/veg-fruit-icons/feijoa.png",
      photo_src: "/images/photos/feijoa.jpg",
      difficulty: "Medium",
      planting_starts: "spring",
      planting_ends: "early-summer",
      watering_frequency: "Regularly, keep soil moist",
      sun_level: "full-sun to partial-shade",
      cycle: "Perennial",
      days_from_seed_until_seedling: 30,
      days_from_planting_until_harvest: 365
    },
    {
      id: 23,
      name: "Kale",
      icon_src: "/images/flat-icons/veg-fruit-icons/kale.png",
      photo_src: "/images/photos/kale.jpg",
      difficulty: "Medium",
      planting_starts: "spring",
      planting_ends: "early-summer",
      watering_frequency: "Regularly, keep soil moist",
      sun_level: "full-sun to partial-shade",
      cycle: "Annual",
      days_from_seed_until_seedling: 14,
      days_from_planting_until_harvest: 60
    },
    {
      id: 24,
      name: "Kumara",
      icon_src: "/images/flat-icons/veg-fruit-icons/kumara.png",
      photo_src: "/images/photos/kumara.jpg",
      difficulty: "Medium",
      planting_starts: "spring",
      planting_ends: "early-summer",
      watering_frequency: "Regularly, keep soil moist",
      sun_level: "full-sun",
      cycle: "Annual",
      days_from_seed_until_seedling: 30,
      days_from_planting_until_harvest: 120
    },
    {
      id: 25,
      name: "Lettuce",
      icon_src: "/images/flat-icons/veg-fruit-icons/lettuce.png",
      photo_src: "/images/photos/lettuce.jpg",
      difficulty: "Medium",
      planting_starts: "spring",
      planting_ends: "early-summer",
      watering_frequency: "Regularly, keep soil moist",
      sun_level: "partial-sun to full-sun",
      cycle: "Annual",
      days_from_seed_until_seedling: 7,
      days_from_planting_until_harvest: 30
    },
    {
      id: 26,
      name: "Mandarins",
      icon_src: "/images/flat-icons/veg-fruit-icons/mandarin.png",
      photo_src: "/images/photos/mandarins.jpg",
      difficulty: "Medium",
      planting_starts: "spring",
      planting_ends: "early-summer",
      watering_frequency: "Regularly, keep soil moist",
      sun_level: "full-sun",
      cycle: "Perennial",
      days_from_seed_until_seedling: null,
      days_from_planting_until_harvest: 365
    },
    {
      id: 27,
      name: "Mesclun",
      icon_src: "/images/flat-icons/veg-fruit-icons/mesclun.png",
      photo_src: "/images/photos/mesclun.jpg",
      difficulty: "Easy",
      planting_starts: "early-spring",
      planting_ends: "late-summer",
      watering_frequency: "Regularly, keep soil moist",
      sun_level: "partial-sun to full-sun",
      cycle: "Annual",
      days_from_seed_until_seedling: 7,
      days_from_planting_until_harvest: 21
    },
    {
      id: 28,
      name: "Onion",
      icon_src: "/images/flat-icons/veg-fruit-icons/onion.png",
      photo_src: "/images/photos/onion.jpg",
      difficulty: "Easy",
      planting_starts: "early-spring",
      planting_ends: "mid-spring",
      watering_frequency: "Regularly, keep soil moist",
      sun_level: "full-sun",
      cycle: "Biennial",
      days_from_seed_until_seedling: 14,
      days_from_planting_until_harvest: 90
    },
    {
      id: 29,
      name: "Orange",
      icon_src: "/images/flat-icons/veg-fruit-icons/orange.png",
      photo_src: "/images/photos/orange.jpg",
      difficulty: "Medium",
      planting_starts: "spring",
      planting_ends: "early-summer",
      watering_frequency: "Regularly, keep soil moist",
      sun_level: "full-sun",
      cycle: "Perennial",
      days_from_seed_until_seedling: null,
      days_from_planting_until_harvest: 730
    },
    {
      id: 30,
      name: "Parsley",
      icon_src: "/images/flat-icons/veg-fruit-icons/parsley.png",
      photo_src: "/images/photos/parsley.jpg",
      difficulty: "Easy",
      planting_starts: "early-spring",
      planting_ends: "late-summer",
      watering_frequency: "Regularly, keep soil moist",
      sun_level: "partial-sun to full-sun",
      cycle: "Biennial",
      days_from_seed_until_seedling: 14,
      days_from_planting_until_harvest: 70
    },
    {
      id: 31,
      name: "Passionfruit",
      icon_src: "/images/flat-icons/veg-fruit-icons/passionfruit.png",
      photo_src: "/images/photos/passionfruit.jpg",
      difficulty: "Medium",
      planting_starts: "spring",
      planting_ends: "early-summer",
      watering_frequency: "Regularly, keep soil moist",
      sun_level: "full-sun",
      cycle: "Perennial",
      days_from_seed_until_seedling: null,
      days_from_planting_until_harvest: 365
    },
    {
      id: 32,
      name: "Pears",
      icon_src: "/images/flat-icons/veg-fruit-icons/pear.png",
      photo_src: "/images/photos/pears.jpg",
      difficulty: "Medium",
      planting_starts: "late winter",
      planting_ends: "early spring",
      watering_frequency: "Regularly, keep soil moist",
      sun_level: "full-sun",
      cycle: "Perennial",
      days_from_seed_until_seedling: null,
      days_from_planting_until_harvest: 730
    },
    {
      id: 33,
      name: "Peas",
      icon_src: "/images/flat-icons/veg-fruit-icons/peas.png",
      photo_src: "/images/photos/peas.jpg",
      difficulty: "Easy",
      planting_starts: "early spring",
      planting_ends: "mid-spring",
      watering_frequency: "Regularly, keep soil moist",
      sun_level: "full-sun to partial-shade",
      cycle: "Annual",
      days_from_seed_until_seedling: 7,
      days_from_planting_until_harvest: 60
    },
    {
      id: 34,
      name: "Pumpkin",
      icon_src: "/images/flat-icons/veg-fruit-icons/pumpkin.png",
      photo_src: "/images/photos/pumpkin.jpg",
      difficulty: "Easy",
      planting_starts: "spring",
      planting_ends: "early summer",
      watering_frequency: "Regularly, keep soil moist",
      sun_level: "full-sun",
      cycle: "Annual",
      days_from_seed_until_seedling: 7,
      days_from_planting_until_harvest: 90
    },
    {
      id: 35,
      name: "Radish",
      icon_src: "/images/flat-icons/veg-fruit-icons/radish.png",
      photo_src: "/images/photos/radish.jpg",
      difficulty: "Easy",
      planting_starts: "early spring",
      planting_ends: "late summer",
      watering_frequency: "Regularly, keep soil moist",
      sun_level: "full-sun to partial-shade",
      cycle: "Annual",
      days_from_seed_until_seedling: 5,
      days_from_planting_until_harvest: 25
    },
    {
      id: 36,
      name: "Spinach",
      icon_src: "/images/flat-icons/veg-fruit-icons/spinach.png",
      photo_src: "/images/photos/spinach.jpg",
      difficulty: "Easy",
      planting_starts: "early spring",
      planting_ends: "mid-spring",
      watering_frequency: "Regularly, keep soil moist",
      sun_level: "partial-sun to full-sun",
      cycle: "Annual",
      days_from_seed_until_seedling: 7,
      days_from_planting_until_harvest: 30
    },
    {
      id: 37,
      name: 'Basil',
      icon_src: '/images/flat-icons/veg-fruit-icons/basil.png',
      photo_src: '/images/photos/basil.jpg',
      difficulty: 'Easy',
      planting_starts: 'late-summer',
      planting_ends: 'early-winter',
      watering_frequency: 'Twice a week',
      sun_level: 'part-sun',
      cycle: 'Annual',
      days_from_seed_until_seedling: 20,
      days_from_planting_until_harvest: 90,
    },
    {
      id: 38,
      name: 'Carrot',
      icon_src: '/images/flat-icons/veg-fruit-icons/carrot.png',
      photo_src: '/images/photos/carrots.jpg',
      difficulty: 'Hard',
      planting_starts: 'early-spring',
      planting_ends: 'late-spring',
      watering_frequency: 'Every other day',
      sun_level: 'full-sun',
      cycle: 'Biennial',
      days_from_seed_until_seedling: 0,
      days_from_planting_until_harvest: 190,
    },
  ])

  await knex('plant_care_data').del()
  await knex('plant_care_data').insert([
    {
      id: 1,
      plantName: 'Tomato',
      scientificName: 'Solanum lycopersicum',
      description:
        'The tomato is a widely cultivated plant species, producing edible red fruits, commonly known as tomatoes.',
      soil: 'Well-drained',
      sunlight: 'Full sun',
      watering: 'Medium',
      fertilization: 'Regularly',
      pruning: 'Prune regularly',
      pests: 'Watch for insects',
      diseases: 'Protect from disease',
      indoorsPlantingTime: 'Start seeds indoors August - September',
      outdoorsPlantingTime: 'Transplant outdoors October - November',
      spacing: '0.6 - 1.0 metres',
      plantingTime: 'October - November',
      harvestingTime: 'Summer',
      harvestingTips: 'Harvest when red',
    },
    {
      id: 2,
      plantName: 'Potato',
      scientificName: 'Solanum tuberosum',
      description: 'A starchy tuberous crop grown for its edible tubers.',
      soil: 'Well drained, loose soil',
      sunlight: 'Full sun',
      watering: 'Medium',
      fertilization: 'Regularly',
      pruning: 'Remove any diseased foliage',
      pests: 'Aphids, Colorado potato beetles',
      diseases: 'Late blight, early blight',
      indoorsPlantingTime: 'Not applicable',
      outdoorsPlantingTime: 'Spring',
      spacing: '0.3 - 0.6 meters',
      plantingTime: 'August - October',
      harvestingTime: 'Summer',
      harvestingTips: 'Harvest when tubers are firm and mature',
    },
    {
      id: 3,
      plantName: 'Zucchini',
      scientificName: 'Cucurbita pepo',
      description:
        'Zucchini is a summer squash with a mild flavor and a versatile range of culinary uses.',
      soil: 'Well-drained',
      sunlight: 'Full sun',
      watering: 'Medium',
      fertilization: 'Regularly',
      pruning: 'Pinch off blossoms',
      pests: 'Squash bugs',
      diseases: 'Powdery mildew',
      indoorsPlantingTime: 'Start seeds indoors August - September',
      outdoorsPlantingTime: 'Transplant outdoors October - November',
      spacing: '0.6 - 1 meter',
      plantingTime: 'Spring',
      harvestingTime: 'Summer to autumn',
      harvestingTips: 'Harvest zucchini when small and tender',
    },
    {
      id: 4,
      plantName: 'Cauliflower',
      scientificName: 'Brassica oleracea var. botrytis',
      description: 'Cauliflower is a cool-season vegetable known for its dense, white curd-like heads.',
      soil: 'Well-drained, fertile soil rich in organic matter',
      sunlight: 'Full sun',
      watering: 'Regularly, keep soil evenly moist',
      fertilization: 'Moderate, with balanced fertilizer',
      pruning: 'Not necessary for head formation',
      pests: 'Cabbage worms, aphids',
      diseases: 'Downy mildew, clubroot',
      indoorsPlantingTime: 'Start seeds indoors 4-6 weeks before the last frost date',
      outdoorsPlantingTime: 'Transplant outdoors after last frost, early spring',
      spacing: '0.3 - 0.45 meter',
      plantingTime: 'Spring to early summer',
      harvestingTime: 'Late summer to early autumn',
      harvestingTips: 'Harvest cauliflower heads when they are firm and compact'
    },
    {
      id: 5,
      plantName: 'Broccoli',
      scientificName: 'Brassica oleracea var. italica',
      description: 'Broccoli is a cool-season vegetable prized for its nutritious florets and stalks.',
      soil: 'Well-drained, fertile soil rich in organic matter',
      sunlight: 'Full sun to partial shade',
      watering: 'Regularly, keep soil evenly moist',
      fertilization: 'Moderate, with balanced fertilizer',
      pruning: 'Not necessary for head formation',
      pests: 'Cabbage worms, aphids',
      diseases: 'Clubroot, downy mildew',
      indoorsPlantingTime: 'Start seeds indoors 6-8 weeks before the last frost date',
      outdoorsPlantingTime: 'Transplant outdoors after last frost, early spring',
      spacing: '0.3 - 0.45 meter',
      plantingTime: 'Spring to early summer',
      harvestingTime: 'Late spring to early summer',
      harvestingTips: 'Harvest broccoli heads when they are firm and tight before they start to flower'
    },
    {
      id: 6,
      plantName: "Silverbeet",
      scientificName: "Beta vulgaris subsp. vulgaris",
      description: "Silverbeet, also known as Swiss chard, is a leafy green vegetable known for its colorful stems and nutritious leaves.",
      soil: "Well-drained, fertile soil rich in organic matter",
      sunlight: "Full sun to partial shade",
      watering: "Regularly, keep soil moist",
      fertilization: "Moderate, with balanced fertilizer",
      pruning: "Remove old or yellowing leaves",
      pests: "Aphids, leaf miners",
      diseases: "Downy mildew, leaf spot",
      indoorsPlantingTime: "Start seeds indoors 4-6 weeks before the last frost date",
      outdoorsPlantingTime: "Transplant outdoors after last frost, early spring",
      spacing: "30-45 cm (12-18 inches) apart",
      plantingTime: "Spring to early summer",
      harvestingTime: "Summer to autumn",
      harvestingTips: "Harvest outer leaves for continuous growth, or harvest whole plants when mature"
    },
    {
      id: 7,
      plantName: "Asparagus",
      scientificName: "Asparagus officinalis",
      description: "Asparagus is a perennial vegetable prized for its tender shoots, often harvested in spring.",
      soil: "Well-drained, fertile soil",
      sunlight: "Full sun",
      watering: "Regularly, keep soil evenly moist",
      fertilization: "Annually, with balanced fertilizer",
      pruning: "Cut back old foliage in late winter",
      pests: "Asparagus beetle, aphids",
      diseases: "Fusarium wilt, rust",
      indoorsPlantingTime: "Start seeds indoors 10-12 weeks before the last frost date",
      outdoorsPlantingTime: "Plant crowns or seeds in early spring",
      spacing: "30-45 cm (12-18 inches) apart",
      plantingTime: "Early spring",
      harvestingTime: "Second or third year after planting",
      harvestingTips: "Harvest spears when they reach about 8-10 inches tall by snapping or cutting at soil level"
    },
    {
      id: 8,
      plantName: "Blackberry",
      scientificName: "Rubus fruticosus",
      description: "Blackberries are perennial plants known for their delicious and juicy fruits.",
      soil: "Well-drained, fertile soil with good organic content",
      sunlight: "Full sun to partial shade",
      watering: "Regularly, keep soil moist",
      fertilization: "Monthly, with balanced fertilizer during growing season",
      pruning: "Prune canes after fruiting to encourage new growth",
      pests: "Spider mites, aphids",
      diseases: "Anthracnose, cane blight",
      indoorsPlantingTime: "Start seeds indoors in early spring for transplanting",
      outdoorsPlantingTime: "Plant in late autumn or early spring",
      spacing: "1.2 - 1.5 meters (4 - 5 feet) apart",
      plantingTime: "Late autumn to early spring",
      harvestingTime: "Summer to early autumn",
      harvestingTips: "Harvest berries when fully ripe and easily detach from the plant"
    },
    {
      id: 9,
      plantName: "Blueberry",
      scientificName: "Vaccinium corymbosum",
      description: "Blueberries are perennial shrubs prized for their sweet and nutritious berries.",
      soil: "Acidic, well-drained soil rich in organic matter",
      sunlight: "Full sun to partial shade",
      watering: "Regularly, keep soil consistently moist",
      fertilization: "Monthly, with acidic fertilizer during growing season",
      pruning: "Prune in late winter to early spring to remove dead or weak branches",
      pests: "Birds, aphids",
      diseases: "Powdery mildew, root rot",
      indoorsPlantingTime: "Start seeds indoors in early spring for transplanting",
      outdoorsPlantingTime: "Plant in late autumn or early spring",
      spacing: "1 - 1.5 meters (3 - 5 feet) apart",
      plantingTime: "Late autumn to early spring",
      harvestingTime: "Summer to early autumn",
      harvestingTips: "Harvest berries when they turn blue and easily detach from the plant"
    },
    {
      id: 10,
      plantName: "Bok Choy",
      scientificName: "Brassica rapa subsp. chinensis",
      description: "Bok Choy, also known as Chinese cabbage, is a leafy vegetable with crisp white stalks and dark green leaves.",
      soil: "Well-drained, fertile soil rich in organic matter",
      sunlight: "Partial shade to full sun",
      watering: "Regularly, keep soil evenly moist",
      fertilization: "Monthly, with balanced fertilizer",
      pruning: "Not necessary",
      pests: "Cabbage worms, aphids",
      diseases: "Downy mildew, clubroot",
      indoorsPlantingTime: "Start seeds indoors 4-6 weeks before the last frost date",
      outdoorsPlantingTime: "Transplant outdoors after last frost, early spring",
      spacing: "15-20 cm (6-8 inches) apart",
      plantingTime: "Spring to early summer",
      harvestingTime: "6-8 weeks after planting",
      harvestingTips: "Harvest when heads are firm and before they start to bolt"
    },
    {
      id: 11,
      plantName: "Broad Beans",
      scientificName: "Vicia faba",
      description: "Broad beans, also known as fava beans, are cool-season legumes with large, flavorful pods.",
      soil: "Well-drained, fertile soil",
      sunlight: "Full sun",
      watering: "Regularly, keep soil evenly moist",
      fertilization: "Once or twice during the growing season with balanced fertilizer",
      pruning: "Pinch off growing tips to encourage bushier growth",
      pests: "Aphids, bean beetles",
      diseases: "Chocolate spot, rust",
      indoorsPlantingTime: "Start seeds indoors 4-6 weeks before the last frost date for transplanting",
      outdoorsPlantingTime: "Direct sow in early spring or late autumn",
      spacing: "20-30 cm (8-12 inches) apart",
      plantingTime: "Early spring or late autumn",
      harvestingTime: "12-16 weeks after planting",
      harvestingTips: "Harvest when pods are plump and firm, but before they become tough and bitter"
    },
    {
      id: 12,
      plantName: "Capsicum",
      scientificName: "Capsicum annuum",
      description: "Capsicum, commonly known as bell pepper or sweet pepper, is a tender perennial with glossy fruits in various colors.",
      soil: "Well-drained, fertile soil rich in organic matter",
      sunlight: "Full sun",
      watering: "Regularly, keep soil evenly moist",
      fertilization: "Monthly, with balanced fertilizer",
      pruning: "Pinch off growing tips to encourage bushier growth",
      pests: "Aphids, spider mites",
      diseases: "Bacterial leaf spot, blossom end rot",
      indoorsPlantingTime: "Start seeds indoors 8-10 weeks before the last frost date",
      outdoorsPlantingTime: "Transplant outdoors after last frost, early spring",
      spacing: "30-45 cm (12-18 inches) apart",
      plantingTime: "Spring",
      harvestingTime: "12-16 weeks after planting",
      harvestingTips: "Harvest when fruits reach desired size and color, and have a firm, crisp texture"
    },
    {
      id: 13,
      plantName: "Celery",
      scientificName: "Apium graveolens",
      description: "Celery is a cool-season biennial vegetable prized for its crisp stalks and distinctive flavor.",
      soil: "Rich, moist soil high in organic matter",
      sunlight: "Full sun to partial shade",
      watering: "Regularly, keep soil consistently moist",
      fertilization: "Every 2-3 weeks with balanced fertilizer",
      pruning: "Not necessary",
      pests: "Aphids, celery leafminer",
      diseases: "Leaf spot, damping-off",
      indoorsPlantingTime: "Start seeds indoors 10-12 weeks before the last frost date",
      outdoorsPlantingTime: "Transplant outdoors after last frost, early spring",
      spacing: "15-20 cm (6-8 inches) apart",
      plantingTime: "Early spring",
      harvestingTime: "12-14 weeks after planting",
      harvestingTips: "Harvest stalks when they reach desired size and are crisp and crunchy"
    },
    {
      id: 14,
      plantName: "Coriander",
      scientificName: "Coriandrum sativum",
      description: "Coriander, also known as cilantro or Chinese parsley, is an herb with aromatic leaves and seeds used in cooking.",
      soil: "Well-drained, fertile soil",
      sunlight: "Full sun to partial shade",
      watering: "Regularly, keep soil moist",
      fertilization: "Monthly, with balanced fertilizer",
      pruning: "Pinch off flowers to prolong leaf growth",
      pests: "Aphids, spider mites",
      diseases: "Powdery mildew, damping-off",
      indoorsPlantingTime: "Start seeds indoors in early spring for transplanting",
      outdoorsPlantingTime: "Direct sow in early spring or late summer",
      spacing: "15-20 cm (6-8 inches) apart",
      plantingTime: "Spring or late summer",
      harvestingTime: "3-4 weeks after planting",
      harvestingTips: "Harvest leaves when they are young and tender for best flavor"
    },
    {
      id: 15,
      plantName: "Corn",
      scientificName: "Zea mays",
      description: "Corn is a warm-season annual cereal crop known for its tall stalks and ears with sweet, juicy kernels.",
      soil: "Well-drained, fertile soil with good organic content",
      sunlight: "Full sun",
      watering: "Regularly, keep soil evenly moist",
      fertilization: "Every 2-3 weeks with balanced fertilizer",
      pruning: "Not necessary",
      pests: "Corn earworm, armyworm",
      diseases: "Common rust, smut",
      indoorsPlantingTime: "Start seeds indoors 2-4 weeks before the last frost date for transplanting",
      outdoorsPlantingTime: "Direct sow after last frost, when soil is warm",
      spacing: "20-30 cm (8-12 inches) apart",
      plantingTime: "Spring, when soil temperature reaches 60°F (16°C) or higher",
      harvestingTime: "60-100 days after planting, depending on variety",
      harvestingTips: "Harvest ears when silks are brown and kernels are plump and juicy"
    },
    {
      id: 16,
      plantName: "Courgette",
      scientificName: "Cucurbita pepo",
      description: "Courgette, also known as zucchini, is a summer squash with a mild flavor and versatile culinary uses.",
      soil: "Well-drained, fertile soil",
      sunlight: "Full sun",
      watering: "Regularly, keep soil evenly moist",
      fertilization: "Monthly, with balanced fertilizer",
      pruning: "Pinch off growing tips to encourage bushier growth",
      pests: "Squash bugs, cucumber beetles",
      diseases: "Powdery mildew, blossom end rot",
      indoorsPlantingTime: "Start seeds indoors 4-6 weeks before the last frost date for transplanting",
      outdoorsPlantingTime: "Transplant outdoors after last frost, early spring",
      spacing: "60-90 cm (24-36 inches) apart",
      plantingTime: "Spring",
      harvestingTime: "6-8 weeks after planting",
      harvestingTips: "Harvest when fruits are small to medium-sized and tender"
    },
    {
      id: 17,
      plantName: "Spring Onion",
      scientificName: "Allium fistulosum",
      description: "Spring onion, also known as green onion or scallion, is a mild-flavored onion harvested young for its slender white bulbs and green tops.",
      soil: "Well-drained, fertile soil",
      sunlight: "Full sun to partial shade",
      watering: "Regularly, keep soil evenly moist",
      fertilization: "Monthly, with balanced fertilizer",
      pruning: "Not necessary",
      pests: "Thrips, onion maggots",
      diseases: "Downy mildew, pink root",
      indoorsPlantingTime: "Start seeds indoors in early spring for transplanting",
      outdoorsPlantingTime: "Direct sow in early spring or late summer",
      spacing: "5-10 cm (2-4 inches) apart",
      plantingTime: "Spring or late summer",
      harvestingTime: "6-8 weeks after planting",
      harvestingTips: "Harvest when bulbs are developed and tops are green and healthy"
    },
    {
      id: 18,
      plantName: "Apple",
      scientificName: "Malus domestica",
      description: "Apples are popular fruits grown on deciduous trees known for their crisp texture and various flavors.",
      soil: "Well-drained loamy soil",
      sunlight: "Full sun",
      watering: "Regularly, especially during dry periods",
      fertilization: "Annually in spring with balanced fertilizer",
      pruning: "Prune in late winter to early spring to shape and remove dead/diseased branches",
      pests: "Codling moth, apple maggot",
      diseases: "Apple scab, powdery mildew",
      plantingTime: "Late winter to early spring",
      harvestingTime: "Late summer to fall, depending on variety",
      harvestingTips: "Harvest apples when they are fully colored and firm, with a slight twist to detach from the tree"
    },
    {
      id: 19,
      plantName: "Arugula",
      scientificName: "Eruca vesicaria subsp. sativa",
      description: "Arugula, also known as rocket or rucola, is a fast-growing salad green with a peppery flavor.",
      soil: "Well-drained, fertile soil",
      sunlight: "Full sun to partial shade",
      watering: "Regularly, keep soil evenly moist",
      fertilization: "Every 3-4 weeks with a nitrogen-rich fertilizer",
      pests: "Flea beetles, aphids",
      diseases: "Downy mildew, damping-off",
      plantingTime: "Early spring to late summer",
      harvestingTime: "4-6 weeks after planting",
      harvestingTips: "Harvest young leaves for the best flavor and texture"
    },
    {
      id: 20,
      plantName: "Cucumber",
      scientificName: "Cucumis sativus",
      description: "Cucumber is a warm-season vegetable known for its crisp texture and mild flavor, commonly used in salads and pickling.",
      soil: "Well-drained, fertile soil",
      sunlight: "Full sun",
      watering: "Regularly, keep soil evenly moist",
      fertilization: "Every 2-3 weeks with balanced fertilizer",
      pests: "Cucumber beetles, aphids",
      diseases: "Powdery mildew, bacterial wilt",
      plantingTime: "Spring, after the last frost date",
      harvestingTime: "6-8 weeks after planting",
      harvestingTips: "Harvest cucumbers when they are firm, green, and before they turn yellow"
    },
    {
      id: 21,
      plantName: "Eggplant",
      scientificName: "Solanum melongena",
      description: "Eggplant, also known as aubergine, is a warm-season vegetable prized for its glossy, purple fruits and versatile culinary uses.",
      soil: "Well-drained, fertile soil rich in organic matter",
      sunlight: "Full sun",
      watering: "Regularly, keep soil evenly moist",
      fertilization: "Monthly, with balanced fertilizer",
      pests: "Aphids, flea beetles",
      diseases: "Verticillium wilt, powdery mildew",
      plantingTime: "Late spring, after the last frost date",
      harvestingTime: "12-16 weeks after planting",
      harvestingTips: "Harvest eggplants when they reach full size and have a glossy appearance"
    },
    {
      id: 22,
      plantName: "Feijoa",
      scientificName: "Acca sellowiana",
      description: "Feijoa, also known as pineapple guava, is a tropical evergreen shrub or small tree valued for its sweet and aromatic fruits.",
      soil: "Well-drained, fertile soil with a slightly acidic pH",
      sunlight: "Full sun to partial shade",
      watering: "Regularly, especially during dry periods",
      fertilization: "Twice a year, in early spring and mid-summer, with a balanced fertilizer",
      pests: "Fruit flies, mealybugs",
      diseases: "Leaf spot, root rot",
      plantingTime: "Spring or early summer",
      harvestingTime: "4-5 years after planting, when fruits are mature",
      harvestingTips: "Harvest feijoa when fruits are slightly soft to touch and have a fragrant aroma"
    },
    {
      id: 23,
      plantName: "Kale",
      scientificName: "Brassica oleracea var. acephala",
      description: "Kale is a nutritious leafy green vegetable known for its hearty texture and rich nutritional content.",
      soil: "Well-drained, fertile soil rich in organic matter",
      sunlight: "Full sun to partial shade",
      watering: "Regularly, keep soil evenly moist",
      fertilization: "Every 4-6 weeks with a balanced fertilizer",
      pests: "Cabbage worms, aphids",
      diseases: "Downy mildew, clubroot",
      plantingTime: "Early spring or late summer",
      harvestingTime: "6-8 weeks after planting, leaves can be harvested as needed",
      harvestingTips: "Harvest outer leaves first, allowing inner leaves to continue growing"
    },
    {
      id: 24,
      plantName: "Kumara",
      scientificName: "Ipomoea batatas",
      description: "Kumara, also known as sweet potato, is a starchy root vegetable known for its sweet taste and versatility in cooking.",
      soil: "Well-drained, loose, and sandy soil",
      sunlight: "Full sun",
      watering: "Regularly, keep soil evenly moist",
      fertilization: "Once a month with a balanced fertilizer",
      pests: "Sweet potato weevils, whiteflies",
      diseases: "Fusarium wilt, sweet potato scurf",
      plantingTime: "Spring, after the last frost date",
      harvestingTime: "3-4 months after planting, when tubers are mature",
      harvestingTips: "Harvest sweet potatoes carefully to avoid damaging the tubers"
    },
    {
      id: 25,
      plantName: "Lettuce",
      scientificName: "Lactuca sativa",
      description: "Lettuce is a leafy green vegetable that is widely cultivated for its tender leaves, commonly used in salads and sandwiches.",
      soil: "Well-drained, fertile soil",
      sunlight: "Partial shade to full sun",
      watering: "Regularly, keep soil moist but not waterlogged",
      fertilization: "Every 3-4 weeks with a balanced fertilizer",
      pests: "Aphids, slugs",
      diseases: "Downy mildew, lettuce mosaic virus",
      plantingTime: "Early spring or early fall for cooler climates; year-round in mild climates",
      harvestingTime: "6-8 weeks after planting, or when leaves are large enough to harvest",
      harvestingTips: "Harvest outer leaves first, allowing inner leaves to continue growing"
    },
    {
      id: 26,
      plantName: "Mandarins",
      scientificName: "Citrus reticulata",
      description: "Mandarins are small citrus fruits known for their sweet flavor and easy-to-peel skin.",
      soil: "Well-drained, loamy soil",
      sunlight: "Full sun",
      watering: "Regularly, especially during dry periods",
      fertilization: "Three times a year with citrus-specific fertilizer",
      pests: "Citrus leafminer, aphids",
      diseases: "Citrus greening, root rot",
      plantingTime: "Spring or fall, in a warm and sunny location",
      harvestingTime: "Several months after flowering, when fruits are fully colored and easily detach from the tree",
      harvestingTips: "Harvest mandarins by gently twisting them off the tree to avoid damaging the fruit or branch"
    },
    {
      id: 27,
      plantName: "Mesclun",
      scientificName: "Mix of various salad greens",
      description: "Mesclun is a mix of young, tender salad greens that often includes lettuce, arugula, endive, and other leafy vegetables.",
      soil: "Well-drained, fertile soil",
      sunlight: "Partial shade to full sun",
      watering: "Regularly, keep soil evenly moist",
      fertilization: "Every 3-4 weeks with a balanced fertilizer",
      pests: "Aphids, slugs",
      diseases: "Downy mildew, leaf spot",
      plantingTime: "Early spring or early fall",
      harvestingTime: "3-4 weeks after planting, when leaves are young and tender",
      harvestingTips: "Harvest mesclun by cutting leaves near the base, allowing plants to regrow for multiple harvests"
    },
    {
      id: 28,
      plantName: "Onion",
      scientificName: "Allium cepa",
      description: "Onions are versatile root vegetables known for their pungent flavor and essential role in cooking worldwide.",
      soil: "Well-drained, fertile soil",
      sunlight: "Full sun",
      watering: "Regularly, keep soil evenly moist but not waterlogged",
      fertilization: "Every 4-6 weeks with a balanced fertilizer",
      pests: "Onion maggots, thrips",
      diseases: "Downy mildew, onion white rot",
      plantingTime: "Early spring or fall, depending on the variety",
      harvestingTime: "3-4 months after planting, when tops begin to yellow and fall over",
      harvestingTips: "Harvest onions by gently pulling them from the soil and allowing them to cure in a dry, airy place"
    },
    {
      id: 29,
      plantName: "Orange",
      scientificName: "Citrus × sinensis",
      description: "Oranges are citrus fruits known for their sweet and tangy flavor, rich in vitamin C and other essential nutrients.",
      soil: "Well-drained, sandy or loamy soil",
      sunlight: "Full sun",
      watering: "Regularly, deep watering especially during dry periods",
      fertilization: "Three times a year with citrus-specific fertilizer",
      pests: "Citrus leafminer, aphids, spider mites",
      diseases: "Citrus canker, root rot, citrus greening",
      plantingTime: "Spring or fall, in warm climates",
      harvestingTime: "7-12 months after flowering, when fruits are fully colored and easily detach from the tree",
      harvestingTips: "Harvest oranges by gently twisting them off the tree to avoid damaging the fruit or branch"
    },
    {
      id: 30,
      plantName: "Parsley",
      scientificName: "Petroselinum crispum",
      description: "Parsley is a popular herb used in a variety of culinary dishes for its fresh, slightly peppery flavor.",
      soil: "Well-drained, fertile soil rich in organic matter",
      sunlight: "Full sun to partial shade",
      watering: "Regularly, keep soil evenly moist",
      fertilization: "Every 4-6 weeks with a balanced fertilizer",
      pests: "Aphids, caterpillars",
      diseases: "Leaf spot, root rot",
      plantingTime: "Spring or fall",
      harvestingTime: "70-90 days after planting",
      harvestingTips: "Harvest parsley by cutting the outer stems at the base, allowing inner stems to continue growing"
    },
    {
      id: 31,
      plantName: "Passionfruit",
      scientificName: "Passiflora edulis",
      description: "Passionfruit is a tropical vine known for its deliciously sweet and tangy fruit, often used in drinks and desserts.",
      soil: "Well-drained, fertile soil rich in organic matter",
      sunlight: "Full sun",
      watering: "Regularly, keep soil evenly moist but not waterlogged",
      fertilization: "Every 4-6 weeks with a balanced fertilizer",
      pests: "Aphids, passion vine hoppers",
      diseases: "Fusarium wilt, root rot",
      plantingTime: "Spring or early summer",
      harvestingTime: "12-18 months after planting",
      harvestingTips: "Harvest when the fruit is fully colored and begins to wrinkle slightly; the fruit should fall off easily"
    },
    {
      id: 32,
      plantName: "Pears",
      scientificName: "Pyrus communis",
      description: "Pears are a popular fruit known for their sweet, juicy flesh and a variety of culinary uses.",
      soil: "Well-drained, loamy soil rich in organic matter",
      sunlight: "Full sun",
      watering: "Regularly, especially during dry periods",
      fertilization: "Twice a year with a balanced fertilizer",
      pests: "Pear psylla, codling moth",
      diseases: "Fire blight, pear scab",
      plantingTime: "Early spring or late fall",
      harvestingTime: "3-4 years after planting (for mature trees)",
      harvestingTips: "Harvest pears when they are mature but still firm; they will ripen off the tree"
    },
    {
      id: 33,
      plantName: "Peas",
      scientificName: "Pisum sativum",
      description: "Peas are a cool-season crop known for their sweet and tender seeds, commonly used in a variety of dishes.",
      soil: "Well-drained, fertile soil",
      sunlight: "Full sun to partial shade",
      watering: "Regularly, keep soil evenly moist",
      fertilization: "At planting time with a balanced fertilizer",
      pests: "Aphids, pea weevils",
      diseases: "Powdery mildew, root rot",
      plantingTime: "Early spring or late summer for fall harvest",
      harvestingTime: "60-70 days after planting",
      harvestingTips: "Harvest peas when the pods are plump but still tender; pick regularly to encourage continued production"
    },
    {
      id: 34,
      plantName: "Pumpkin",
      scientificName: "Cucurbita pepo",
      description: "Pumpkins are large, round gourds with a thick, orange shell and a sweet, dense flesh, commonly used for pies, soups, and decorations.",
      soil: "Well-drained, fertile soil rich in organic matter",
      sunlight: "Full sun",
      watering: "Regularly, especially during dry periods; keep soil evenly moist",
      fertilization: "Every 3-4 weeks with a balanced fertilizer",
      pests: "Squash bugs, cucumber beetles",
      diseases: "Powdery mildew, downy mildew",
      plantingTime: "Late spring, after the last frost",
      harvestingTime: "90-120 days after planting",
      harvestingTips: "Harvest pumpkins when they are fully colored and the rind is hard; cut the stem with a sharp knife, leaving a few inches of stem attached"
    },
    {
      id: 35,
      plantName: "Radish",
      scientificName: "Raphanus sativus",
      description: "Radishes are fast-growing root vegetables known for their crisp texture and peppery flavor, often used in salads and garnishes.",
      soil: "Well-drained, loose soil",
      sunlight: "Full sun to partial shade",
      watering: "Regularly, keep soil evenly moist",
      fertilization: "Light fertilization at planting time with a balanced fertilizer",
      pests: "Aphids, flea beetles",
      diseases: "Downy mildew, root rot",
      plantingTime: "Spring and fall",
      harvestingTime: "20-30 days after planting",
      harvestingTips: "Harvest radishes when they are about 1 inch in diameter for the best flavor; pull them gently from the soil"
    },
    {
      id: 36,
      plantName: "Spinach",
      scientificName: "Spinacia oleracea",
      description: "Spinach is a leafy green vegetable known for its rich nutritional content, including vitamins A, C, and K, and its versatility in cooking.",
      soil: "Well-drained, fertile soil rich in organic matter",
      sunlight: "Full sun to partial shade",
      watering: "Regularly, keep soil evenly moist",
      fertilization: "Every 2-3 weeks with a balanced fertilizer",
      pests: "Aphids, leaf miners",
      diseases: "Downy mildew, leaf spot",
      plantingTime: "Early spring or fall",
      harvestingTime: "30-45 days after planting",
      harvestingTips: "Harvest spinach by cutting outer leaves when they are young and tender; allow inner leaves to continue growing for multiple harvests"
    },
    {
      id: 37,
      plantName: "Basil",
      scientificName: "Ocimum basilicum",
      description: "Basil is a fragrant herb commonly used in a variety of cuisines for its sweet and savory flavor.",
      soil: "Well-drained, fertile soil rich in organic matter",
      sunlight: "Full sun",
      watering: "Regularly, keep soil evenly moist but not waterlogged",
      fertilization: "Every 4-6 weeks with a balanced fertilizer",
      pests: "Aphids, spider mites",
      diseases: "Downy mildew, fusarium wilt",
      plantingTime: "Spring after the last frost",
      harvestingTime: "60-90 days after planting",
      harvestingTips: "Harvest basil leaves regularly to encourage bushy growth; cut stems just above a pair of leaves"
    },
    {
      id: 38,
      plantName: "Carrot",
      scientificName: "Daucus carota",
      description: "Carrots are root vegetables known for their sweet, crunchy roots and vibrant orange color.",
      soil: "Loose, well-drained soil free from stones",
      sunlight: "Full sun",
      watering: "Regularly, keep soil evenly moist",
      fertilization: "Once or twice during the growing season with a balanced fertilizer",
      pests: "Carrot rust fly, aphids",
      diseases: "Root rot, powdery mildew",
      plantingTime: "Early spring to midsummer",
      harvestingTime: "60-80 days after sowing, depending on variety",
      harvestingTips: "Harvest carrots when they reach mature size and color; gently loosen soil around them and pull carefully to avoid damage"
    }
  ])

  await knex('user_desired_plants').del()
  await knex('user_desired_plants').insert([
    { id: 1, user_id: 1, plant_id: 1 },
    { id: 2, user_id: 1, plant_id: 2 },
    { id: 3, user_id: 1, plant_id: 3 },
    { id: 4, user_id: 2, plant_id: 1 },
    { id: 5, user_id: 2, plant_id: 2 },
    { id: 6, user_id: 2, plant_id: 3 },
    { id: 7, user_id: 3, plant_id: 1 },
    { id: 8, user_id: 3, plant_id: 2 },
    { id: 9, user_id: 3, plant_id: 3 },
  ])
  await knex('plots').del()
  await knex('plots').insert([
    {
      id: 1,
      garden_id: 1,
      plot_number: 1,
      sun_level: 'part-sun',
      plot_type: 'house',
      size: 5,
      growable: false,
      name: 'Kitchen',
    },
    {
      id: 2,
      garden_id: 1,
      plot_number: 2,
      sun_level: 'full-sun',
      plot_type: 'path',
      size: 4,
      growable: true,
      name: 'Wonderland',
    },
    {
      id: 3,
      garden_id: 1,
      plot_number: 3,
      sun_level: 'full-shade',
      plot_type: 'garden',
      size: 4,
      growable: true,
      name: 'Secret Garden',
    },
    {
      id: 4,
      garden_id: 2,
      plot_number: 1,
      sun_level: 'part-sun',
      plot_type: 'garden',
      size: 5,
      growable: true,
      name: 'Edible for sure',
    },
    {
      id: 5,
      garden_id: 2,
      plot_number: 2,
      sun_level: 'full-sun',
      plot_type: 'garden',
      size: 4,
      growable: true,
      name: 'Underground world',
    },
    {
      id: 6,
      garden_id: 2,
      plot_number: 3,
      sun_level: 'full-shade',
      plot_type: 'garden',
      size: 2,
      growable: true,
      name: 'Floral planet',
    },
    {
      id: 7,
      garden_id: 3,
      plot_number: 1,
      sun_level: 'part-sun',
      plot_type: 'grass',
      size: 5,
      growable: true,
      name: 'Greenhouse',
    },
    {
      id: 8,
      garden_id: 3,
      plot_number: 2,
      sun_level: 'full-sun',
      plot_type: 'grass',
      size: 4,
      growable: true,
      name: 'Underground gold',
    },
    {
      id: 9,
      garden_id: 3,
      plot_number: 3,
      sun_level: 'full-shade',
      plot_type: 'garden',
      size: 2,
      growable: true,
      name: 'Secret garden',
    },
  ])
  await knex('plots_plants').del()
  await knex('plots_plants').insert([
    {
      id: 1,
      plant_id: 1,
      plot_id: 1,
      date_planted: '2024-03-01',
      last_watered: '2024-03-15',
      watering_history: '[2024-03-15]',
      user_id: 1,
      name: 'tomato 1',
    },
    {
      id: 2,
      plant_id: 2,
      plot_id: 2,
      date_planted: '2024-04-01',
      last_watered: '2024-04-10',
      watering_history: '[2024-03-15]',
      user_id: 1,
      name: 'tomato 2',
    },
    {
      id: 3,
      plant_id: 3,
      plot_id: 3,
      date_planted: '2024-02-15',
      last_watered: '2024-02-20',
      watering_history: '[2024-03-15]',
      user_id: 1,
      name: 'tomato 3',
    },
    {
      id: 4,
      plant_id: 1,
      plot_id: 4,
      date_planted: '2024-03-01',
      last_watered: '2024-03-15',
      watering_history: '[2024-03-15]',
      user_id: 2,
      name: 'cucumber 1',
    },
    {
      id: 5,
      plant_id: 2,
      plot_id: 5,
      date_planted: '2024-04-01',
      last_watered: '2024-04-10',
      watering_history: '[2024-03-15]',
      user_id: 2,
      name: 'cucumber 2',
    },
    {
      id: 6,
      plant_id: 3,
      plot_id: 6,
      date_planted: '2024-02-15',
      last_watered: '2024-02-20',
      watering_history: '[2024-03-15]',
      user_id: 2,
      name: 'cucumber 3',
    },
    {
      id: 7,
      plant_id: 1,
      plot_id: 7,
      date_planted: '2024-03-01',
      last_watered: '2024-03-15',
      watering_history: '[2024-03-15]',
      user_id: 3,
      name: 'potato 1',
    },
    {
      id: 8,
      plant_id: 2,
      plot_id: 8,
      date_planted: '2024-04-01',
      last_watered: '2024-04-10',
      watering_history: '[2024-03-15]',
      user_id: 3,
      name: 'potato 2',
    },
    {
      id: 9,
      plant_id: 3,
      plot_id: 9,
      date_planted: '2024-02-15',
      last_watered: '2024-02-20',
      watering_history: '[2024-03-15]',
      user_id: 3,
      name: 'potato 3',
    },
  ])

  // await knex('plant_notes').del()
  // await knex('plant_notes').insert([
  //   {id: 1, plot_plant_id: 1, date: '2024-03-16', note: 'Plant is growing well.' },
  //   {id: 2, plot_plant_id: 2, date: '2024-04-12', note: 'Leaves are green and healthy.' },
  //   {id: 3, plot_plant_id: 3, date: '2024-02-22', note: 'Showing signs of growth.' },
  //   {id: 4, plot_plant_id: 4, date: '2024-03-16', note: 'Plant is growing well.' },
  //   {id: 5, plot_plant_id: 5, date: '2024-04-12', note: 'Leaves are green and healthy.' },
  //   {id: 6, plot_plant_id: 6, date: '2024-02-22', note: 'Showing signs of growth.' },
  //   {id: 7, plot_plant_id: 7, date: '2024-03-16', note: 'Plant is growing well.' },
  //   {id: 8, plot_plant_id: 8, date: '2024-04-12', note: 'Leaves are green and healthy.' },
  //   {id: 9, plot_plant_id: 9, date: '2024-02-22', note: 'Showing signs of growth.' },
  // ]);
  // await knex('images').del()
  // await knex('images').insert([
  //   {id: 1, plot_notes_id: 1, image: 'image1.jpg' },
  //   {id: 2, plot_notes_id: 2, image: 'image2.jpg' },
  //   {id: 3, plot_notes_id: 3, image: 'image3.jpg' }
  // ]);
}
